---
title: "cov_mx"
author: "KERA YUCEL"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview

This package is developed to help users calculate correlation coefficients and covariance matrix of a given data with missing values. In order to implement correlation coefficients and covariance matrix, the standard deviation of the data is needed however the world of data is not always clean and tidy. `base` R fails to return standard deviation and calculation of the correlation coefficients when the data has missing values. This package aims to overcome this obstacle and help users handle missing values when calculating correlation coefficients and covariance matrix. `CorrR` uses likewise deletion method to handle missing values: removing the rows of a data frame where the missing values are present.

# Covariance Matrix (cov_mx)

A Covariance matrix displays the variance and covariance together. This function would use the above two functions.

$$Cov(X,Y) = \frac{\sum(x-\overline{x})(y-\overline{y})}{N} $$

# Function 

`cov_mx` function calculates the covariance matrix of the two variables and automatically deals with the missing value

- INPUT
    - x a matrix that contains one or more than one random variable
  
- OUTPUT 
    - z matrix that contains the covariance between random variables in the input matrix
  
- EXAMPLE
    - cov_mx(matrix(c(1, 2, NA, 4, 5, 6, 7, 8), 4))
